export default {
    BEERS_LIST: 'BEERS_LIST',
    CURRENT_PAGE: 'CURRENT_PAGE',
    TOGGLE_LOADER: 'TOGGLE LOADER',
    RANDOM_BEER: 'RANDOM_BEER',
    ADD_BASKET: 'CHANGE_BASKET',
    DELETE_BASKET: 'DELETE_BASKET'
}